/**
 * Mode of AI consultation or conversation.
 */
export enum AISessionType {
  PLANNING = 'planning',
  COACHING = 'coaching',
  REFLECTION = 'reflection',
  CHAT = 'chat',
}

/**
 * Message author role.
 */
export enum AIMessageSender {
  USER = 'user',
  ASSISTANT = 'assistant',
  SYSTEM = 'system',
}

/**
 * Categorization of recommendations suggested by Gemini.
 */
export enum AIRecommendationType {
  TASK_PRIORITY = 'task_priority',
  SCHEDULE_OPTIMIZATION = 'schedule_optimization',
  PRODUCTIVITY_INSIGHT = 'productivity_insight',
  GOAL_REFINEMENT = 'goal_refinement',
  WELLNESS_BREAK = 'wellness_break',
}

/**
 * Acceptance states for AI suggested actions.
 */
export enum AIRecommendationStatus {
  PENDING = 'pending',
  ACCEPTED = 'accepted',
  DISMISSED = 'dismissed',
  APPLIED = 'applied',
}

/**
 * Message block representing a speech turn in an AI session.
 */
export interface AIMessage {
  /** Unique message identifier */
  id: string;
  /** Role of the entity sending the message */
  sender: AIMessageSender;
  /** Raw text content generated or sent */
  content: string;
  /** ISO Date string when the message was sent */
  timestamp: string;
  /** Optional interactive prompt responses/suggestions for the user to select next */
  suggestions: string[] | null;
}

/**
 * Interactive chat/coaching session log stored in Firestore.
 */
export interface AISession {
  /** Unique AI session log identifier */
  id: string;
  /** ID of the user participating in the session */
  userId: string;
  /** Purpose classification of the session */
  type: AISessionType;
  /** User-facing title summarizing the discussion topic */
  title: string;
  /** Messages timeline */
  messages: AIMessage[];
  /** ISO Date string when the session log started */
  createdAt: string;
  /** ISO Date string when the session log was last updated */
  updatedAt: string;
}

/**
 * Structured recommendation generated by the Gemini engine for user approval.
 */
export interface AIRecommendation {
  /** Unique recommendation identifier */
  id: string;
  /** ID of the target user */
  userId: string;
  /** Classification of the recommendation */
  type: AIRecommendationType;
  /** Execution status of the recommendation */
  status: AIRecommendationStatus;
  /** Direct concise title of the suggestion */
  title: string;
  /** Comprehensive explanation detailing benefits or actions */
  description: string;
  /** Engine confidence level (float from 0.0 to 1.0) */
  confidenceScore: number;
  /** Optional JSON payload with structured data changes to make (e.g. updating task fields) */
  actionPayload: Record<string, any> | null;
  /** ISO Date string when the recommendation was created */
  createdAt: string;
  /** ISO Date string when the recommendation was last updated/dismissed */
  updatedAt: string;
}
